import {takeEvery, all} from 'redux-saga/effects';
import * as actions                from '../actions/actions';

import {
    loginUserSaga,
    checkUserSaga,
    logoutUserSaga,
    preLoginUserSaga
} from './login';

import {
    getDataBranchSaga,
    getDataCompanySaga,
    getDataRoleSaga,
    getDataUserAppsSaga,
    getDataUserAppsWithParamSaga,
    getDataUserMobileSaga,
    submitAddBranchSaga,
    submitAddCompanySaga,
    submitAddRoleSaga,
    submitAddUserAppsSaga,
    submitAddUserMobileSaga,
    submitDeleteBranchSaga,
    submitDeleteCompanySaga,
    submitDeleteRoleSaga,
    submitDeleteUserMobileSaga,
    submitDeleteUserSaga,
    submitEditBranchSaga,
    submitEditCompanySaga,
    submitEditRoleSaga,
    submitEditUserAppsSaga,
    submitEditUserMobileSaga,
    submitPostCompanySaga,
    getAddressDataSaga,
    getParameterClientSaga,
    submitAddParameterClientSaga,
    submitEditParameterClientSaga,
    submitDeleteParameterClientSaga,
    getCustomerSaga,
    submitCustomerSaga,
    getProductSaga,
    submitProductSaga,
    getVendorSaga,
    submitVendorSaga,
    getInventoriSaga,
    submitInventoriSaga,
    getCategoryProductSaga,
    submitCategoryProductSaga,
    getMappingStockSaga,
    submitMappingStockSaga,
    getPriceListSaga,
    submitPriceListSaga,
    getPurchaseReceiveSaga,
    submitPurchaseReceiveSaga,
    getDepositDataSaga,
    submitDepositSaga,
    getAreaSaga,
    submitAreaSaga,
    getDraftPurchaseReceiveSaga,
    submitDraftPurchaseReceiveSaga,
    getStockAdjusmentSaga,
    submitStockAdjusmentSaga,
    getPackingListSaga,
    submitPackingListSaga,
    getInvoiceSaga,
    submitInvoiceSaga
} from './admin';


export function* watchLogin() {
    yield all([
        takeEvery(actions.LOGIN_USER, loginUserSaga),
        takeEvery(actions.CHECK_AUTH_SUCCESS, checkUserSaga),
        takeEvery(actions.LOGOUT, logoutUserSaga),
        takeEvery(actions.PRE_LOGIN_USER, preLoginUserSaga)
    ]);
}

export function* watchAdmin() {
    yield all([
        takeEvery(actions.GET_BRANCH_DATA, getDataBranchSaga),
        takeEvery(actions.SUBMIT_ADD_BRANCH, submitAddBranchSaga),
        takeEvery(actions.SUBMIT_EDIT_BRANCH, submitEditBranchSaga),
        takeEvery(actions.GET_COMPANY_DATA, getDataCompanySaga),
        takeEvery(actions.SUBMIT_ADD_COMPANY, submitAddCompanySaga),
        takeEvery(actions.SUBMIT_EDIT_COMPANY, submitEditCompanySaga),
        takeEvery(actions.GET_ROLE_DATA, getDataRoleSaga),
        takeEvery(actions.SUBMIT_ADD_ROLE, submitAddRoleSaga),
        takeEvery(actions.SUBMIT_EDIT_ROLE, submitEditRoleSaga),
        takeEvery(actions.GET_USERAPPS_DATA, getDataUserAppsSaga),
        takeEvery(actions.SUBMIT_ADD_USERAPPS_DATA, submitAddUserAppsSaga),
        takeEvery(actions.GET_USERAPPS_WITH_PARAM_DATA, getDataUserAppsWithParamSaga),
        takeEvery(actions.SUBMIT_EDIT_USERAPPS_DATA, submitEditUserAppsSaga),
        takeEvery(actions.SUBMIT_POST_COMPANY, submitPostCompanySaga),
        takeEvery(actions.SUBMIT_DELETE_COMPANY, submitDeleteCompanySaga),
        takeEvery(actions.GET_USERMOBILE_DATA, getDataUserMobileSaga),
        takeEvery(actions.SUBMIT_ADD_USERMOBILE, submitAddUserMobileSaga),
        takeEvery(actions.SUBMIT_EDIT_USERMOBILE, submitEditUserMobileSaga),
        takeEvery(actions.GET_ADDRESS_DATA, getAddressDataSaga),

        takeEvery(actions.GET_PARAMETERCLIENT_DATA, getParameterClientSaga),
        takeEvery(actions.SUBMIT_ADD_PARAMETERCLIENT, submitAddParameterClientSaga),
        takeEvery(actions.SUBMIT_EDIT_PARAMETERCLIENT, submitEditParameterClientSaga),
        takeEvery(actions.SUBMIT_DELETE_PARAMETERCLIENT, submitDeleteParameterClientSaga),
        takeEvery(actions.GET_CUSTOMER_DATA, getCustomerSaga),
        takeEvery(actions.SUBMIT_CUSTOMER, submitCustomerSaga),
        takeEvery(actions.GET_PRODUCT_DATA, getProductSaga),
        takeEvery(actions.SUBMIT_PRODUCT, submitProductSaga),
        takeEvery(actions.GET_VENDOR_DATA, getVendorSaga),
        takeEvery(actions.SUBMIT_VENDOR, submitVendorSaga),
        takeEvery(actions.GET_INVENTORI_DATA, getInventoriSaga),
        takeEvery(actions.SUBMIT_INVENTORI, submitInventoriSaga),
        takeEvery(actions.GET_CATEGORYPRODUCT_DATA, getCategoryProductSaga),
        takeEvery(actions.SUBMIT_CATEGORYPRODUCT, submitCategoryProductSaga),
        takeEvery(actions.GET_MAPPINGSTOCK_DATA, getMappingStockSaga),
        takeEvery(actions.SUBMIT_MAPPINGSTOCK, submitMappingStockSaga),
        takeEvery(actions.GET_PRICELIST_DATA, getPriceListSaga),
        takeEvery(actions.SUBMIT_PRICELIST, submitPriceListSaga),
        takeEvery(actions.GET_PURCHASERECEIVE_DATA, getPurchaseReceiveSaga),
        takeEvery(actions.SUBMIT_PURCHASERECEIVE, submitPurchaseReceiveSaga),
        takeEvery(actions.GET_DEPOSIT_DATA, getDepositDataSaga),
        takeEvery(actions.SUBMIT_DEPOSIT, submitDepositSaga),
        takeEvery(actions.GET_AREA_DATA, getAreaSaga),
        takeEvery(actions.SUBMIT_AREA, submitAreaSaga),
        takeEvery(actions.GET_DRAFTPURCHASERECEIVE_DATA, getDraftPurchaseReceiveSaga),
        takeEvery(actions.SUBMIT_DRAFTPURCHASERECEIVE, submitDraftPurchaseReceiveSaga),
        takeEvery(actions.GET_STOCKADJUSMENT_DATA, getStockAdjusmentSaga),
        takeEvery(actions.SUBMIT_STOCKADJUSMENT, submitStockAdjusmentSaga),
        takeEvery(actions.GET_PACKINGLIST_DATA, getPackingListSaga),
        takeEvery(actions.SUBMIT_PACKINGLIST, submitPackingListSaga),
        takeEvery(actions.GET_INVOICE_DATA, getInvoiceSaga),
        takeEvery(actions.SUBMIT_INVOICE, submitInvoiceSaga),
    ]);
}